- name: update packages
  apt:
    update_cache: yes
    upgrade: yes

- name: install apt packages
  package:
    name: "{{ packages }}"
    state: latest

- name: install snap packages
  community.general.snap:
    name: "{{ snap_packages }}"
    classic: yes

- name: disable password auth on ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: enable passwordless sudo for "{{ username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: restart sshd 
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed
