- name: update packages
  apt:
    update_cache: yes
    upgrade: yes

- name: install apt packages
  package:
    name: "{{ packages }}"
    state: latest

- name: disable password auth on ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: enable passwordless sudo for "{{ username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: restart sshd
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed

- name: install nvm
  become: true
  become_user: "{{ username }}"
  shell: |
    NVM_VERSION=$(curl -s https://api.github.com/repos/nvm-sh/nvm/releases/latest | jq -r '.tag_name')
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_VERSION}/install.sh | bash
  args:
    creates: "/home/{{ username }}/.nvm/nvm.sh"
  register: nvm_result
  changed_when: "'already installed' not in nvm_result.stdout"

- name: install node lts
  become: true
  become_user: "{{ username }}"
  shell: >
    source ~/.nvm/nvm.sh && nvm install stable
  args:
    executable: /usr/bin/bash
  register: node_version_response
  changed_when: "'already installed' not in node_version_response.stderr"
