---
- name: Update package cache
  apt:
    update_cache: yes
  when: update_packages | bool
  tags: [packages, update]

- name: Upgrade packages
  apt:
    upgrade: yes
  when: upgrade_packages | bool
  tags: [packages, upgrade]

- name: Install common packages
  package:
    name: "{{ common_packages }}"
    state: latest
  tags: [packages, install]
